### ISSUE TITLE
We are unable to fulfill your request

### ISSUE THREAD

**Issue by yesyeahvh123** [josephcz-xyz/storage#1]
i have error when authorized ondrive account please help
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Comment by baobao1270** [comment]
You have to add the `redirect_uri` to your app. Read Microsoft docs for detail. Ensure SSL is enabled.

Without logs or screenshot, I am unable to provide more solutions.

**Comment by baobao1270** [comment]
Since you have no response, we closed this issue. You can reopen it by replying it.
